### ISSUE TITLE
CMake Error at CMakeL ists.txt:51 (target compile features):

### ISSUE THREAD

**Issue by sym19991125** [eigen2017/fastllmtritonbackend#2]
![QQ图片20230905164545](https://github.com/eigen2017/fastllmtritonbackend/assets/59417038/0e6c64b6-7dc8-485d-9cfb-c5bfb3a6758f)

**Comment by sym19991125** [comment]
CMake版本更新为3.26.4

**Comment by sym19991125** [comment]
要下载一个googletest的包，链接URL https://github.com/google/googletest/archive/9406a60c7839052e4944ea4dbc8344762a89f9bd.zip
然后将common包里的/src/test/CMakeLists.txt中的URL后面的链接改成本地zip的路径

**Comment by sym19991125** [comment]
fastllmtritonbackend库中的CMakeLists，line 51，cXX改为cxx

**Comment by eigen2017** [comment]
thx

**Comment by eigen2017** [comment]
代码你已经给我了，我更新一下repo
