### ISSUE TITLE
没有libfastllm.so

### ISSUE THREAD

**Issue by sym19991125** [eigen2017/fastllmtritonbackend#3]
将fastllm中CMakeLists.txt（line 65）中的
        add_library(fastllm object
            ${FASTLLM_CXX_SOURCES}
            ${FASTLLM_CUDA_SOURCES}
            )
            
将object改为SHARED，再重新编译

**Comment by sym19991125** [comment]
在修改CMakeLists时，target_include_directories里面的fastllm/include/路径要修改为自己的

**Comment by eigen2017** [comment]
谢谢，是这样的。
